import { Injectable } from '@angular/core';

const errors = {
  "1":'Call your bank',
  "2":'Call your bank',
  "3":'Invalid merchant',
  "4":'Your card is restricted',
  "5":'Transaction declined',
  "6":'Error - retry',
  "7":'Your card is disabled',
  "8":'Additional identification required',
  "9":'Request in progress',
  "10":'Partially approved',
  "11":'Approved (VIP)',
  "12":'Invalid transaction',
  "13":'Invalid amount',
  "14":'No such card',
  "15":'No such card/issuer',
  "16":'Approved, update track 3',
  "17":'Customer cancellation',
  "18":'Customer dispute',
  "19":'Re-enter transaction',
  "20":'Invalid response',
  "21":'No action taken',
  "22":'Suspected malfunction',
  "23":'Unacceptable fee',
  "24":'Update not supported',
  "25":'No such record',
  "26":'Duplicate update/replaced',
"27":'Field update error',
"28":'File locked out',
"29":'Error, contact acquirer',
"30":'Format error',
"31":'Issuer signed-off',
"32":'Completed partially',
"33":'Expired card',
"34":'Suspected fraud',
"35":'Acceptor contact acquirer',
"36":'Restricted card',
"37":'Call your bank',
"38":'PIN tries exceeded',
"39":'No credit account',
"40":'Function not supported',
"41":'Lost card',
"42":'No universal account',
"43":'Stolen card',
"44":'No investment account',
"45":'Reserved',
"46":'Reserved',
"47":'Reserved',
"48":'Reserved',
"49":'Reserved',
"50":'Reserved',
"51":'Not sufficient funds',
"52":'No chequing account',
"53":'No savings account',
"54":'Expired card',
"55":'Incorrect PIN',
"56":'No card record',
"57":'Not permitted to client',
"58":'Not permitted to merchant',
"59":'Suspected fraud',
"60":'Acceptor call acquirer',
"61":'Exceeds amount limit',
"62":'Restricted card',
"63":'Security violation',
"64":'Wrong original amount',
"65":'Exceeds frequency limit',
"66":'Acceptor call acquirer',
"67":'Pick up at ATM',
"68":'Reply received too late',
"69":'Reserved',
"70":'Reserved',
"71":'Reserved',
"72":'Reserved',
"73":'Reserved',
"74":'Reserved',
"75":'PIN tries exceeded',
"76":'Wrong PIN,tries exceeded',
"77":'Wrong Reference No.',
"78":'Reserved',
"79":'Already reversed',
"80":'Network error',
"81":'Foreign network error',
"82":'Time-out at issuer',
"83":'Transaction failed',
"84":'Pre-authorization timed out',
"85":'Account verification required',
"86":'Unable to verify PIN',
"87":'Reserved',
"88":'Cryptographic failure',
"89":'Authentication failure',
"90":'Cutoff is in progress',
"91":'Issuer unavailable',
"92":'Router unavailable',
"93":'Violation of law',
"94":'Duplicate transmission',
"95":'Reconcile error',
"96":'System malfunction',
"97":'Reserved',
"98":'Reserved',
"99":'Aborted',
"-1":'General fault',
"-2":'Mandatory field is empty',
"-3":'Bad CGI request',
"-4":'No or Invalid response received',
"-5":'Server is not responding',
"-6":'Connect failed',
"-7":'Configuration error',
"-8":'Invalid response',
"-9":'Error in card number field',
"-10":'Error in card expiration date field',
"-11":'Error in amount field',
"-12":'Error in currency field',
"-13":'Error in merchant terminal field',
"-14":'Unknown referer',
"-15":'PINpad agent/device error',
"-16":'Terminal is locked, please try again',
"-17":'Terminal is locked, please try again',
"-18":'Access denied',
"-19":'',
"-20":'Authentication failed'
}

@Injectable({
  providedIn: 'root'
})

export class BankErrorCodesService {

  constructor() { }

  getErrMassage(code){
    return errors[code]
  }
}
